version: '3'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=6996Ludmila
      - MYSQL_DATABASE=mercadolivre
      - MYSQL_USER=ludmila
      - MYSQL_PASSWORD=6996Ludmila
    expose:
      - 3306
    container_name: db
    networks:
      - spring-boot-mysql-network
  app:
    build:
      dockerfile: ./docker/mercadoLivre.dockerfile
      context: .
    networks:
      - spring-boot-mysql-network
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - "db"

networks:
  spring-boot-mysql-network:
    driver: bridge